-- Q131. Display city-wise revenue for UPI transactions.
select city, sum(price) as revenue, payment_mode
from sales
where payment_mode='UPI'
group by city ;

-- Q132. Display city-wise revenue for Electronics products.
select city,sum(price) as revenue, category
from sales
where category='Gadgets'
group by city;

-- Q133. Display city-wise revenue generated by female customers.
 select city,sum(price) as revenue, gender
 from sales
 where gender = 'Female'
 group by city;
 
 -- Q134. Display city-wise revenue for orders above 5,000.
 select city,sum(price) as revenue
 from sales
 where price>5000
 group by city ;
 
 -- Q135. Display cities where revenue from orders above 5,000 exceeds 50,000.
 select city, sum(price) as revenue
 from sales
 where price>5000
 group by city having revenue>50000;
 
 -- Q136. Display categories with more than 2 UPI orders.
 select category,count(payment_mode) as count_of_upi
 from sales
 where payment_mode = 'UPI'
 group by category having count_of_upi>2;

-- Q137. Display categories where Card payment revenue exceeds 10,000.
select category,sum(price) as card_payment_revenue
from sales
where payment_mode='Card'
group by category having card_payment_revenue>10000;

-- Q138. Display category-wise count of products having rating above 4.5.
select category,sum(quantity) as product_count
from sales
where rating > 4.5
group by category;

-- Q139. Display city-wise revenue generated by customers older than 25.
select city,sum(price) as revenue
from sales
where age>25
group by city;

-- Q140. Display cities where revenue generated by customers older than 25 exceeds 20,000.
select city, sum(price) as revenue
from sales
where age>25
group by city having revenue>20000;
 